
CREATE TABLE country ( 
    id INT PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE league (
    id INT PRIMARY KEY,
    country_id INT,
    name VARCHAR(50),
    FOREIGN KEY (country_id) REFERENCES country(id)
);

CREATE TABLE match ( 
    id INT PRIMARY KEY,
    country_id INT,
    league_id INT,
    season VARCHAR(50),
    stage INT,
    date DATE,
    match_api_id INT,
    home_team_api_id INT,
    away_team_api_id INT,
    home_team_goal INT,
    away_team_goal INT,
    home_player_X1 INT,
    home_player_X2 INT,
    home_player_X3 INT,
    home_player_X4 INT,
    home_player_X5 INT,
    home_player_X6 INT,
    home_player_X7 INT,
    home_player_X8 INT, 
    home_player_X9 INT,
    home_player_X10 INT,
    home_player_X11 INT,
    away_player_X1 INT,
    away_player_X2 INT,
    away_player_X3 INT,
    away_player_X4 INT,
    away_player_X5 INT,
    away_player_X6 INT,
    away_player_X7 INT,
    away_player_X8 INT,
    away_player_X9 INT,
    away_player_X10 INT,
    away_player_X11 INT,
    home_player_Y1 INT,
    home_player_Y2 INT,
    home_player_Y3 INT,
    home_player_Y4 INT,
    home_player_Y5 INT,
    home_player_Y6 INT,
    home_player_Y7 INT,
    home_player_Y8 INT,
    home_player_Y9 INT,
    home_player_Y10 INT,
    home_player_Y11 INT,
    away_player_Y1 INT,
    away_player_Y2 INT,
    away_player_Y3 INT,
    away_player_Y4 INT,
    away_player_Y5 INT,
    away_player_Y6 INT,
    away_player_Y7 INT,
    away_player_Y8 INT,
    away_player_Y9 INT,
    away_player_Y10 INT,
    away_player_Y11 INT,
    home_player_1 INT,
    home_player_2 INT,
    home_player_3 INT,
    home_player_4 INT,
    home_player_5 INT,
    home_player_6 INT,
    home_player_7 INT,
    home_player_8 INT,
    home_player_9 INT,
    home_player_10 INT,
    home_player_11 INT,
    away_player_1 INT,
    away_player_2 INT,
    away_player_3 INT,
    away_player_4 INT,
    away_player_5 INT,
    away_player_6 INT,
    away_player_7 INT,
    away_player_8 INT,
    away_player_9 INT,
    away_player_10 INT,
    away_player_11 INT,
    goal TEXT,
    shoton TEXT,
    shotoff TEXT,
    foulcommit TEXT,
    card TEXT,
    "cross" TEXT,
    corner TEXT,
    possession TEXT,
    B365H FLOAT,
    B365D FLOAT,
    B365A FLOAT,
    BWH FLOAT,
    BWD FLOAT,
    BWA FLOAT,
    IWH FLOAT,
    IWD FLOAT,
    IWA FLOAT,
    LBH FLOAT,
    LBD FLOAT,
    LBA FLOAT,
    PSH FLOAT,
    PSD FLOAT,
    PSA FLOAT,
    WHH FLOAT,
    WHD FLOAT,
    WHA FLOAT,
    SJH FLOAT,
    SJD FLOAT,
    SJA FLOAT,
    VCH FLOAT,
    VCD FLOAT,
    VCA FLOAT,
    GBH FLOAT,
    GBD FLOAT,
    GBA FLOAT,
    BSH FLOAT,
    BSD FLOAT,
    BSA FLOAT,
    FOREIGN KEY (country_id) REFERENCES country(id),
    FOREIGN KEY (league_id) REFERENCES league(id)
);

CREATE TABLE player_attributes (
    id INT PRIMARY KEY,
    player_fifa_api_id INT,
    player_api_id INT,
    date DATE,
    overall_rating INT,
    potential INT,
    preferred_foot VARCHAR(50),
    attacking_work_rate VARCHAR(50),
    defensive_work_rate VARCHAR(50),
    crossing INT,
    finishing INT,
    heading_accuracy INT,
    short_passing INT,
    volleys INT,
    dribbling INT,
    curve INT,
    free_kick_accuracy INT,
    long_passing INT,
    ball_control INT,
    acceleration INT,
    sprint_speed INT,
    agility INT,
    reactions INT,
    balance INT,
    shot_power INT,
    jumping INT,
    stamina INT,
    strength INT,
    long_shots INT,
    aggression INT,
    interceptions INT,
    positioning INT,
    vision INT,
    penalties INT,
    marking INT,
    standing_tackle INT,
    sliding_tackle INT,
    gk_diving INT,
    gk_handling INT,
    gk_kicking INT,
    gk_positioning INT,
    gk_reflexes INT
);

CREATE TABLE player (
    id INT PRIMARY KEY,
    player_api_id INT,
    player_name VARCHAR(50),
    player_fifa_api_id INT,
    birthday DATE,
    height FLOAT,
    weight INT
);

CREATE TABLE team_attributes (
    id INT PRIMARY KEY,
    team_fifa_api_id INT,
    team_api_id INT,
    date DATE,
    buildUpPlaySpeed INT,
    buildUpPlaySpeedClass VARCHAR(50),
    buildUpPlayDribbling INT,
    buildUpPlayDribblingClass VARCHAR(50),
    buildUpPlayPassing INT,
    buildUpPlayPassingClass VARCHAR(50),
    buildUpPlayPositioningClass VARCHAR(50),
    chanceCreationPassing INT,
    chanceCreationPassingClass VARCHAR(50),
    chanceCreationCrossing INT,
    chanceCreationCrossingClass VARCHAR(50),
    chanceCreationShooting INT,
    chanceCreationShootingClass VARCHAR(50),
    chanceCreationPositioningClass VARCHAR(50),
    defencePressure INT,
    defencePressureClass VARCHAR(50),
    defenceAggression INT,
    defenceAggressionClass VARCHAR(50),
    defenceTeamWidth INT,
    defenceTeamWidthClass VARCHAR(50),
    defenceDefenderLineClass VARCHAR(50)
);

CREATE TABLE team (
    id INT PRIMARY KEY,
    team_api_id INT,
    team_fifa_api_id INT,
    team_long_name VARCHAR(50),
    team_short_name VARCHAR(50)
);

---------------------------------------------------------
-----------------------NUEVAS-TABLAS---------------------
---------------------------------------------------------

CREATE TABLE foulcommit (
    id INT, 
    foulscommitted INT, 
    event_incident_typefk INT, 
    elapsed INT,
    player2 INT, 
    subtype TEXT, 
    player1 INT, 
    sortorder INT, 
    team INT,
    n INT, 
    type TEXT
);